PULP_APP = test
PULP_APP_SRCS = test.c
PULP_CFLAGS = -O0 -g

PULP_ARCH_CFLAGS = -march=rv32imc -DRV_ISA_RV32
PULP_ARCH_LDFLAGS = -march=rv32imc
PULP_ARCH_OBJDFLAGS = -Mmarch=rv32imc

include $(PULPRT_HOME)/rules/pulp.mk
